name: Vérify project build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: alpine:3.19

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: apk add --no-cache build-base

      - name: Build
        run: make
