name: Tests, Lint and Coverage

on:
  # Normally it should be triggered when build workflow is successful, but it needs to be on default branch to work
  # So we will trigger it on push and pull request
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    container:
      image: alpine:3.19

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apk add --no-cache \
            build-base \
            check-dev

      - name: Run tests
        run: make test

  format-check:
    needs: tests
    runs-on: ubuntu-latest

    container:
      image: alpine:3.19

    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format
        run: apk add --no-cache clang

      - name: Check formatting
        run: make format-check

  lint:
    needs: tests
    runs-on: ubuntu-latest

    container:
      image: alpine:3.19

    steps:
      - uses: actions/checkout@v4

      - name: Install clang-tidy
        run: apk add --no-cache clang-extra-tools build-base

      - name: Run lint
        run: make lint

  coverage:
    needs: tests
    runs-on: ubuntu-latest

    container:
      image: alpine:3.19

    steps:
      - uses: actions/checkout@v4

      - name: Install coverage tools
        run: |
          apk add --no-cache \
            build-base \
            check-dev \
            lcov

      - name: Generate coverage
        run: make coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/coverage/html
