name: Test project and check code quality

on:
  # Normally it should be triggered when build workflow is successful, but it needs to be on default branch to work
  # So we will trigger it on push and pull request
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    container:
      image: debian:bookworm-slim

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential \
            check

      - name: Run tests
        run: make test

  format-check:
    runs-on: ubuntu-latest

    container:
      image: debian:bookworm-slim

    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          apt-get update
          apt-get install -y --no-install-recommends make clang-format

      - name: Check formatting
        run: make format-check

  lint:
    runs-on: ubuntu-latest

    container:
      image: debian:bookworm-slim

    steps:
      - uses: actions/checkout@v4

      - name: Install clang-tidy
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential \
            check \
            clang-tidy

      - name: Run lint
        run: make lint

coverage:
  needs: tests
  runs-on: ubuntu-latest

  container:
    image: debian:bookworm-slim

  steps:
    - uses: actions/checkout@v4

    - name: Install coverage tools
      run: |
        apt-get update
        apt-get install -y --no-install-recommends \
          build-essential \
          check \
          lcov

    - name: Generate coverage
      run: make coverage

    - name: Upload coverage HTML artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: build/coverage/html

    - name: Upload coverage info artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-info
        path: build/coverage/coverage.info

codecov:
  needs: coverage
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4

    - name: Download coverage info artifact
      uses: actions/download-artifact@v4
      with:
        name: coverage-info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.info
        flags: unittests
        name: codecov-umbrella
